channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=22.2.2
- pip:
  - mlflow<3,>=2.2
  - astunparse==1.6.3
  - cffi==1.15.1
  - cloudpickle==2.0.0
  - defusedxml==0.7.1
  - dill==0.3.4
  - ipython==8.10.0
  - opt-einsum==3.3.0
  - torch==1.13.1
  - torchvision==0.14.1
  - tqdm==4.64.1
name: mlflow-env
